---
- name: Playbook to deploy infra-ibmcloud-standard
  vars:
    terraform_template_vars: "{{ playbook_dir }}/group_vars/terraform.template.tfvars"
    credentials_template_vars: "{{ playbook_dir }}/group_vars/credentials.auto.template.tfvars"
    shared_outputs_vars: "{{ playbook_dir }}/group_vars/shared_outputs.json"
    shared_outputs_template: "{{ playbook_dir }}/shared_outputs_template.j2" 
  hosts: localhost
  pre_tasks:
    - name: Create shared outputs file if doesn't exist
      copy:
        dest: "{{ shared_outputs_vars }}"
        force: false
        content: {}
      check_mode: no
  roles:
    - role: 000-ibm-account-setup
    - role: 100-ibm-shared-services
    - role: 110-ibm-vpc-edge-standard
    - role: 115-ibm-vpc-openshift-standard
    - role: 200-openshift-gitops
    - role: 220-dev-tools